// Country data for phone number selection
// Format: { code: ISO country code, name: Country name, dialCode: Country dial code }
export interface Country {
  code: string;
  name: string;
  dialCode: string;
}

export const countries: Country[] = [
  { code: 'US', name: 'United States', dialCode: '+1' },
  { code: 'GB', name: 'United Kingdom', dialCode: '+44' },
  { code: 'CA', name: 'Canada', dialCode: '+1' },
  { code: 'AU', name: 'Australia', dialCode: '+61' },
  { code: 'DE', name: 'Germany', dialCode: '+49' },
  { code: 'FR', name: 'France', dialCode: '+33' },
  { code: 'IT', name: 'Italy', dialCode: '+39' },
  { code: 'ES', name: 'Spain', dialCode: '+34' },
  { code: 'NL', name: 'Netherlands', dialCode: '+31' },
  { code: 'BE', name: 'Belgium', dialCode: '+32' },
  { code: 'CH', name: 'Switzerland', dialCode: '+41' },
  { code: 'AT', name: 'Austria', dialCode: '+43' },
  { code: 'SE', name: 'Sweden', dialCode: '+46' },
  { code: 'NO', name: 'Norway', dialCode: '+47' },
  { code: 'DK', name: 'Denmark', dialCode: '+45' },
  { code: 'FI', name: 'Finland', dialCode: '+358' },
  { code: 'PL', name: 'Poland', dialCode: '+48' },
  { code: 'PT', name: 'Portugal', dialCode: '+351' },
  { code: 'GR', name: 'Greece', dialCode: '+30' },
  { code: 'IE', name: 'Ireland', dialCode: '+353' },
  { code: 'CZ', name: 'Czech Republic', dialCode: '+420' },
  { code: 'HU', name: 'Hungary', dialCode: '+36' },
  { code: 'RO', name: 'Romania', dialCode: '+40' },
  { code: 'BG', name: 'Bulgaria', dialCode: '+359' },
  { code: 'HR', name: 'Croatia', dialCode: '+385' },
  { code: 'SK', name: 'Slovakia', dialCode: '+421' },
  { code: 'SI', name: 'Slovenia', dialCode: '+386' },
  { code: 'EE', name: 'Estonia', dialCode: '+372' },
  { code: 'LV', name: 'Latvia', dialCode: '+371' },
  { code: 'LT', name: 'Lithuania', dialCode: '+370' },
  { code: 'LU', name: 'Luxembourg', dialCode: '+352' },
  { code: 'MT', name: 'Malta', dialCode: '+356' },
  { code: 'CY', name: 'Cyprus', dialCode: '+357' },
  { code: 'IS', name: 'Iceland', dialCode: '+354' },
  { code: 'NZ', name: 'New Zealand', dialCode: '+64' },
  { code: 'ZA', name: 'South Africa', dialCode: '+27' },
  { code: 'NG', name: 'Nigeria', dialCode: '+234' },
  { code: 'KE', name: 'Kenya', dialCode: '+254' },
  { code: 'GH', name: 'Ghana', dialCode: '+233' },
  { code: 'EG', name: 'Egypt', dialCode: '+20' },
  { code: 'MA', name: 'Morocco', dialCode: '+212' },
  { code: 'DZ', name: 'Algeria', dialCode: '+213' },
  { code: 'TN', name: 'Tunisia', dialCode: '+216' },
  { code: 'ET', name: 'Ethiopia', dialCode: '+251' },
  { code: 'TZ', name: 'Tanzania', dialCode: '+255' },
  { code: 'UG', name: 'Uganda', dialCode: '+256' },
  { code: 'RW', name: 'Rwanda', dialCode: '+250' },
  { code: 'ZM', name: 'Zambia', dialCode: '+260' },
  { code: 'ZW', name: 'Zimbabwe', dialCode: '+263' },
  { code: 'MW', name: 'Malawi', dialCode: '+265' },
  { code: 'MZ', name: 'Mozambique', dialCode: '+258' },
  { code: 'AO', name: 'Angola', dialCode: '+244' },
  { code: 'BJ', name: 'Benin', dialCode: '+229' },
  { code: 'BF', name: 'Burkina Faso', dialCode: '+226' },
  { code: 'BI', name: 'Burundi', dialCode: '+257' },
  { code: 'CM', name: 'Cameroon', dialCode: '+237' },
  { code: 'CV', name: 'Cape Verde', dialCode: '+238' },
  { code: 'CF', name: 'Central African Republic', dialCode: '+236' },
  { code: 'TD', name: 'Chad', dialCode: '+235' },
  { code: 'KM', name: 'Comoros', dialCode: '+269' },
  { code: 'CG', name: 'Congo', dialCode: '+242' },
  { code: 'CD', name: 'Congo, Democratic Republic', dialCode: '+243' },
  { code: 'CI', name: "Côte d'Ivoire", dialCode: '+225' },
  { code: 'DJ', name: 'Djibouti', dialCode: '+253' },
  { code: 'GQ', name: 'Equatorial Guinea', dialCode: '+240' },
  { code: 'ER', name: 'Eritrea', dialCode: '+291' },
  { code: 'SZ', name: 'Eswatini', dialCode: '+268' },
  { code: 'GA', name: 'Gabon', dialCode: '+241' },
  { code: 'GM', name: 'Gambia', dialCode: '+220' },
  { code: 'GN', name: 'Guinea', dialCode: '+224' },
  { code: 'GW', name: 'Guinea-Bissau', dialCode: '+245' },
  { code: 'LS', name: 'Lesotho', dialCode: '+266' },
  { code: 'LR', name: 'Liberia', dialCode: '+231' },
  { code: 'LY', name: 'Libya', dialCode: '+218' },
  { code: 'MG', name: 'Madagascar', dialCode: '+261' },
  { code: 'ML', name: 'Mali', dialCode: '+223' },
  { code: 'MR', name: 'Mauritania', dialCode: '+222' },
  { code: 'MU', name: 'Mauritius', dialCode: '+230' },
  { code: 'NE', name: 'Niger', dialCode: '+227' },
  { code: 'SN', name: 'Senegal', dialCode: '+221' },
  { code: 'SC', name: 'Seychelles', dialCode: '+248' },
  { code: 'SL', name: 'Sierra Leone', dialCode: '+232' },
  { code: 'SO', name: 'Somalia', dialCode: '+252' },
  { code: 'SS', name: 'South Sudan', dialCode: '+211' },
  { code: 'SD', name: 'Sudan', dialCode: '+249' },
  { code: 'TG', name: 'Togo', dialCode: '+228' },
  { code: 'IN', name: 'India', dialCode: '+91' },
  { code: 'CN', name: 'China', dialCode: '+86' },
  { code: 'JP', name: 'Japan', dialCode: '+81' },
  { code: 'KR', name: 'South Korea', dialCode: '+82' },
  { code: 'SG', name: 'Singapore', dialCode: '+65' },
  { code: 'MY', name: 'Malaysia', dialCode: '+60' },
  { code: 'TH', name: 'Thailand', dialCode: '+66' },
  { code: 'ID', name: 'Indonesia', dialCode: '+62' },
  { code: 'PH', name: 'Philippines', dialCode: '+63' },
  { code: 'VN', name: 'Vietnam', dialCode: '+84' },
  { code: 'BD', name: 'Bangladesh', dialCode: '+880' },
  { code: 'PK', name: 'Pakistan', dialCode: '+92' },
  { code: 'LK', name: 'Sri Lanka', dialCode: '+94' },
  { code: 'NP', name: 'Nepal', dialCode: '+977' },
  { code: 'MM', name: 'Myanmar', dialCode: '+95' },
  { code: 'KH', name: 'Cambodia', dialCode: '+855' },
  { code: 'LA', name: 'Laos', dialCode: '+856' },
  { code: 'BN', name: 'Brunei', dialCode: '+673' },
  { code: 'TL', name: 'Timor-Leste', dialCode: '+670' },
  { code: 'MO', name: 'Macau', dialCode: '+853' },
  { code: 'HK', name: 'Hong Kong', dialCode: '+852' },
  { code: 'TW', name: 'Taiwan', dialCode: '+886' },
  { code: 'MN', name: 'Mongolia', dialCode: '+976' },
  { code: 'KZ', name: 'Kazakhstan', dialCode: '+7' },
  { code: 'UZ', name: 'Uzbekistan', dialCode: '+998' },
  { code: 'TJ', name: 'Tajikistan', dialCode: '+992' },
  { code: 'TM', name: 'Turkmenistan', dialCode: '+993' },
  { code: 'KG', name: 'Kyrgyzstan', dialCode: '+996' },
  { code: 'AF', name: 'Afghanistan', dialCode: '+93' },
  { code: 'IR', name: 'Iran', dialCode: '+98' },
  { code: 'IQ', name: 'Iraq', dialCode: '+964' },
  { code: 'SA', name: 'Saudi Arabia', dialCode: '+966' },
  { code: 'AE', name: 'United Arab Emirates', dialCode: '+971' },
  { code: 'IL', name: 'Israel', dialCode: '+972' },
  { code: 'JO', name: 'Jordan', dialCode: '+962' },
  { code: 'LB', name: 'Lebanon', dialCode: '+961' },
  { code: 'SY', name: 'Syria', dialCode: '+963' },
  { code: 'YE', name: 'Yemen', dialCode: '+967' },
  { code: 'OM', name: 'Oman', dialCode: '+968' },
  { code: 'KW', name: 'Kuwait', dialCode: '+965' },
  { code: 'QA', name: 'Qatar', dialCode: '+974' },
  { code: 'BH', name: 'Bahrain', dialCode: '+973' },
  { code: 'TR', name: 'Turkey', dialCode: '+90' },
  { code: 'AZ', name: 'Azerbaijan', dialCode: '+994' },
  { code: 'AM', name: 'Armenia', dialCode: '+374' },
  { code: 'GE', name: 'Georgia', dialCode: '+995' },
  { code: 'BY', name: 'Belarus', dialCode: '+375' },
  { code: 'MD', name: 'Moldova', dialCode: '+373' },
  { code: 'UA', name: 'Ukraine', dialCode: '+380' },
  { code: 'RU', name: 'Russia', dialCode: '+7' },
  { code: 'MX', name: 'Mexico', dialCode: '+52' },
  { code: 'BR', name: 'Brazil', dialCode: '+55' },
  { code: 'AR', name: 'Argentina', dialCode: '+54' },
  { code: 'CL', name: 'Chile', dialCode: '+56' },
  { code: 'CO', name: 'Colombia', dialCode: '+57' },
  { code: 'PE', name: 'Peru', dialCode: '+51' },
  { code: 'VE', name: 'Venezuela', dialCode: '+58' },
  { code: 'EC', name: 'Ecuador', dialCode: '+593' },
  { code: 'BO', name: 'Bolivia', dialCode: '+591' },
  { code: 'PY', name: 'Paraguay', dialCode: '+595' },
  { code: 'UY', name: 'Uruguay', dialCode: '+598' },
  { code: 'CR', name: 'Costa Rica', dialCode: '+506' },
  { code: 'PA', name: 'Panama', dialCode: '+507' },
  { code: 'GT', name: 'Guatemala', dialCode: '+502' },
  { code: 'HN', name: 'Honduras', dialCode: '+504' },
  { code: 'NI', name: 'Nicaragua', dialCode: '+505' },
  { code: 'SV', name: 'El Salvador', dialCode: '+503' },
  { code: 'BZ', name: 'Belize', dialCode: '+501' },
  { code: 'JM', name: 'Jamaica', dialCode: '+1' },
  { code: 'HT', name: 'Haiti', dialCode: '+509' },
  { code: 'DO', name: 'Dominican Republic', dialCode: '+1' },
  { code: 'CU', name: 'Cuba', dialCode: '+53' },
  { code: 'TT', name: 'Trinidad and Tobago', dialCode: '+1' },
  { code: 'BB', name: 'Barbados', dialCode: '+1' },
  { code: 'BS', name: 'Bahamas', dialCode: '+1' },
];

// Helper function to get country by code
export function getCountryByCode(code: string): Country | undefined {
  return countries.find(country => country.code === code);
}

// Helper function to get default country (Tanzania as fallback)
export function getDefaultCountry(): Country {
  return getCountryByCode('TZ') || countries[0];
}